# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
          - pipe: atlassian/trigger-pipeline:4.1.1
            variables:
              BITBUCKET_USERNAME: 'abitsure'
              BITBUCKET_APP_PASSWORD: 'eUcQHFWvjUjER93zH692'
              REPOSITORY: 'order-api'
              # ACCOUNT: '<string>' # Optional
              # BRANCH_NAME: '<string>' # Optional
              # CUSTOM_PIPELINE_NAME: '<string>' # Optional
              # PIPELINE_VARIABLES: '<json>' # Optional
              # WAIT: '<boolean>' # Optional
              # WAIT_MAX_TIMEOUT: '<string>' # Optional
              # DEBUG: '<boolean>' # Optional

